[platformio]
default_envs = xiao_esp32c3_local

[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/KermMartian/ArTICL
    bblanchon/ArduinoJson @ ^7.0.4
    plageoj/UrlEncode @ ^1.0.1

[env:xiao_esp32c3_local]
build_flags =
    -D SERVER=\"http://192.168.1.100:8080\"

[env:xiao_esp32c3_cloud]
build_flags =
    -D SERVER=\"https://your-app.onrender.com\"
    -D SECURE
