[platformio]
default_envs = xiao_esp32s3_local

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/KermMartian/ArTICL
    bblanchon/ArduinoJson @ ^7.0.4
    plageoj/UrlEncode @ ^1.0.1

[env:xiao_esp32c3_local]
board = seeed_xiao_esp32c3
build_flags =
    -D SERVER=\"http://ti84pi.local:8080\"

[env:xiao_esp32c3_cloud]
board = seeed_xiao_esp32c3
build_flags =
    -D SERVER=\"https://your-app.onrender.com\"
    -D SECURE

[env:xiao_esp32s3_local]
board = seeed_xiao_esp32s3
build_flags =
    -D SERVER=\"http://ti84pi.local:8080\"

[env:xiao_esp32s3_cloud]
board = seeed_xiao_esp32s3
build_flags =
    -D SERVER=\"https://your-app.onrender.com\"
    -D SECURE

[env:xiao_esp32s3_camera_local]
board = seeed_xiao_esp32s3
build_flags =
    -D SERVER=\"http://ti84pi.local:8080\"
    -D CAMERA
